#!/usr/bin/env python
__author__ = "Vini Salazar"
__license__ = "MIT"
__maintainer__ = "Vini Salazar"
__url__ = "https://github.com/vinisalazar/bioprov"
__version__ = "0.1.20"

"""
Executable that goes in $PATH. Code for the command-line is on the bioprov.py module.
"""

from bioprov.bioprov import main

main()
