#!/usr/bin/env python
"""
BioProv command-line application. This module holds the main executable.
"""
import argparse
import sys
from bioprov.cli import BioProvParser
from bioprov.utils import parser_help


if __name__ == "__main__":
    parser = BioProvParser()

    # Refactoring to subparsers
    args = None
    if len(sys.argv) == 1 or sys.argv[1] == "-h" or sys.argv == "--help":
        parser_help(parser)
    else:
        args = parser.parse_args()

    parser.parse_options(args)
