#!/usr/bin/env python
"""
BioProv command-line application. This module holds the main executable.
"""
from bioprov.cli import CLI
from bioprov.utils import parser_help

if __name__ == "__main__":
    cli = CLI()
    parser = cli.parser
    parser_help(parser)
    args = parser.parse_args()
