#!/usr/bin/env python
"""
BioProv command-line application. This module holds the main executable.
"""
import argparse
import sys
from bioprov.cli import CLI


def main():
    """
    Imports an instance of CLI and returns it.
    :return: parser object.
    """
    cli = CLI()
    parser_ = cli.parser
    return parser_


if __name__ == "__main__":
    parser = main()
    if len(sys.argv) == 0:
        parser.print_help()
        sys.exit(0)
    args = parser.parse_args()
